version: "3.8"
services:
  proxy:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./logs/nginx:/var/log/nginx
        - ./wp-data:/var/www/html
    links:
        - wordpress
    restart: always
  wordpress:
    image: wordpress:php8.1-apache
    ports:
        - '8080:80'
    volumes:
        - ./wp-data:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=${MYSQL_DB_NAME}
        - WORDPRESS_DB_HOST=uas.ce01upaixfqe.us-east-1.rds.amazonaws.com
        - WORDPRESS_DB_USER=${MYSQL_DB_ADMIN}
        - WORDPRESS_DB_PASSWORD=${MYSQL_DB_PASSWORD}
    restart: always
